aec:
  - conference: "ACM Conference on Computer and Communications Security"
    conference_short: CCS
    link: https://www.sigsac.org/ccs/CCS2024/
    years: 2024
  - conference: "Network and Distributed System Security Symposium"
    conference_short: NDSS
    link: https://www.ndss-symposium.org/
    years: 2024
  - conference: "Annual Computer Security Applications Conference"
    conference_short: ACSAC
    link: https://www.acsac.org/
    years: 2023
tpc:
  - conference: "ACM Internet Measurement Conference Shadow TPC"
    conference_short: IMC
    link: https://conferences.sigcomm.org/imc/2025/shadow-tpc/
    years: 2025
adhoc:
  - conference: "IEEE Symposium on Security and Privacy"
    conference_short: IEEE S&P (Oakland)
    link: https://sp2026.ieee-security.org
    years: 2026
